#!/usr/bin/with-contenv bashio
# ==============================================================================
# ComfoAir 350 Bridge add-on launcher
#
# - Generates config.ini for adorobis/hacomfoairmqtt from the add-on options
#   (auto-detects the Mosquitto broker via the Supervisor MQTT service when no
#   broker is configured).
# - ca350.py reads config.ini from its own directory, so the file is written
#   next to the script in /opt/hacomfoairmqtt.
# - Power-user escape hatch: a config.ini placed in the add-on config folder
#   (/addon_configs/<slug>/) is used verbatim and overrides all options.
# ==============================================================================
set -e

APP_DIR="/opt/hacomfoairmqtt"
CONF_DIR="/config"
CONFIG_FILE="${APP_DIR}/config.ini"

# ------------------------------------------------------------------------------
# Read options
# ------------------------------------------------------------------------------
SERIAL_PORT="$(bashio::config 'serial_port')"
REFRESH_INTERVAL="$(bashio::config 'refresh_interval')"
DEVICE_ID="$(bashio::config 'device_id')"
DEVICE_NAME="$(bashio::config 'device_name')"
DEVICE_MODEL="$(bashio::config 'device_model')"

FAN_IN_ABSENT="$(bashio::config 'fan_in_absent')"
FAN_IN_LOW="$(bashio::config 'fan_in_low')"
FAN_IN_MID="$(bashio::config 'fan_in_mid')"
FAN_IN_HIGH="$(bashio::config 'fan_in_high')"
FAN_OUT_ABSENT="$(bashio::config 'fan_out_absent')"
FAN_OUT_LOW="$(bashio::config 'fan_out_low')"
FAN_OUT_MID="$(bashio::config 'fan_out_mid')"
FAN_OUT_HIGH="$(bashio::config 'fan_out_high')"

# booleans -> Python/ini literals ca350.py compares against ('True'/'False')
RS485_PROTOCOL="False"; bashio::config.true 'rs485_protocol'            && RS485_PROTOCOL="True"
ENABLE_PC_MODE="False"; bashio::config.true 'enable_pc_mode'            && ENABLE_PC_MODE="True"
SETUP_FAN_LEVELS="False"; bashio::config.true 'setup_fan_levels_at_start' && SETUP_FAN_LEVELS="True"
HA_SENSORS="False"; bashio::config.true 'ha_discovery_sensors'          && HA_SENSORS="True"
HA_CLIMATE="False"; bashio::config.true 'ha_discovery_climate'          && HA_CLIMATE="True"
DEBUG="False"; bashio::config.true 'debug'                              && DEBUG="True"

# ------------------------------------------------------------------------------
# MQTT broker: explicit option, else Supervisor-provided service (Mosquitto)
# ------------------------------------------------------------------------------
MQTT_HOST=""
MQTT_PORT="1883"
MQTT_USER="$(bashio::config 'mqtt_user')"
MQTT_PASSWORD="$(bashio::config 'mqtt_password')"

if bashio::config.has_value 'mqtt_broker'; then
    BROKER="$(bashio::config 'mqtt_broker')"
    MQTT_HOST="${BROKER%%:*}"
    if [[ "${BROKER}" == *:* ]]; then
        MQTT_PORT="${BROKER##*:}"
    fi
elif bashio::services.available "mqtt"; then
    MQTT_HOST="$(bashio::services 'mqtt' 'host')"
    MQTT_PORT="$(bashio::services 'mqtt' 'port')"
    if ! bashio::var.has_value "${MQTT_USER}"; then
        MQTT_USER="$(bashio::services 'mqtt' 'username')"
        MQTT_PASSWORD="$(bashio::services 'mqtt' 'password')"
    fi
    bashio::log.info "Using Supervisor MQTT service: ${MQTT_HOST}:${MQTT_PORT}"
else
    bashio::log.warning "No MQTT broker configured and no MQTT service found."
    bashio::log.warning "Install the Mosquitto broker add-on, or set the 'mqtt_broker' option."
fi

# ------------------------------------------------------------------------------
# Serial port sanity check (non-fatal: ca350.py retries, and udev may be slow)
# ------------------------------------------------------------------------------
if [[ ! -e "${SERIAL_PORT}" ]]; then
    bashio::log.warning "Serial port ${SERIAL_PORT} does not exist (yet)."
    bashio::log.warning "Available serial devices:"
    ls -l /dev/serial/by-id/ 2>/dev/null || bashio::log.warning "  /dev/serial/by-id is empty"
fi

# ------------------------------------------------------------------------------
# Generate config.ini
# ------------------------------------------------------------------------------
cat > "${CONFIG_FILE}" <<INI
# Generated by the ComfoAir 350 Bridge add-on from its options - DO NOT EDIT.
# (Edit the add-on configuration instead. To fully override, place your own
#  config.ini into the add-on config folder /addon_configs/<slug>/.)

[DEFAULT]
SerialPort=${SERIAL_PORT}
RS485_protocol=${RS485_PROTOCOL}
refresh_interval=${REFRESH_INTERVAL}
enablePcMode=${ENABLE_PC_MODE}
debug=${DEBUG}

[DEVICE]
FanOutAbsent=${FAN_OUT_ABSENT}
FanOutLow=${FAN_OUT_LOW}
FanOutMid=${FAN_OUT_MID}
FanOutHigh=${FAN_OUT_HIGH}
FanInAbsent=${FAN_IN_ABSENT}
FanInLow=${FAN_IN_LOW}
FanInMid=${FAN_IN_MID}
FanInHigh=${FAN_IN_HIGH}
SetUpFanLevelsAtStart=${SETUP_FAN_LEVELS}

[MQTT]
MQTTServer=${MQTT_HOST}
MQTTPort=${MQTT_PORT}
MQTTKeepalive=45
MQTTUser=${MQTT_USER}
MQTTPassword=${MQTT_PASSWORD}

[HA]
HAEnableAutoDiscoverySensors=${HA_SENSORS}
HAEnableAutoDiscoveryClimate=${HA_CLIMATE}
HAAutoDiscoveryDeviceId=${DEVICE_ID}
HAAutoDiscoveryDeviceName=${DEVICE_NAME}
HAAutoDiscoveryDeviceManufacturer=Zehnder
HAAutoDiscoveryDeviceModel=${DEVICE_MODEL}
INI

# Keep a readable copy next to the escape hatch so users can start from it.
if [[ -d "${CONF_DIR}" ]]; then
    cp -f "${CONFIG_FILE}" "${CONF_DIR}/config.ini.generated" || true
fi

# ------------------------------------------------------------------------------
# Escape hatch: user-supplied config.ini wins
# ------------------------------------------------------------------------------
if [[ -f "${CONF_DIR}/config.ini" ]]; then
    bashio::log.warning "Custom config.ini found in the add-on config folder - it OVERRIDES the add-on options!"
    cp -f "${CONF_DIR}/config.ini" "${CONFIG_FILE}"
fi

# ------------------------------------------------------------------------------
# Launch
# ------------------------------------------------------------------------------
export PYTHONUNBUFFERED=1
cd "${APP_DIR}"

bashio::log.info "Starting ComfoAir bridge on ${SERIAL_PORT} (RS485=${RS485_PROTOCOL}, PC mode=${ENABLE_PC_MODE})"
exec python3 ca350.py
